export enum PoliticianMapping {
  fullName = "Nombre",
  party = "Partido",
  gender = "Género",
  occupation = "Cargo",
  community = "CCAA",
  institution = "Intitución",
  baseSalary = "Sueldo Base",
  monthlyPayment = "Retribución Mensual",
  yearlyPayment = "Retribución Anual",
  complementSalary = "Complemento",
  extraPay = "Pagas Extras",
  otherAllowancesAndIndemnities = "Otras Dietas e Indemnizaciones",
  threeYearsSalary = "Trienio",
  observations = "Observaciones",
}
